name: Lint

on:
  push:
    paths:
      - '**/*.py'
      - 'bin/*'
      - 'sim/vcs/run_vcs'
      - '.ruff.toml'
      - '!addins/*'
  pull_request:
    paths:
      - '**/*.py'
      - 'bin/*'
      - 'sim/vcs/run_vcs'
      - '.ruff.toml'
      - '!addins/*'

jobs:
  lint:
    name: Python ${{matrix.version}} lint
    strategy:
      matrix:
        version: [39, 312] # Test on oldest and newest verions used in wally-package-install.sh
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set Python version
      run: sed -i '/^target-version/c\target-version = "py${{matrix.version}}"' .ruff.toml
    - name: Run ruff
      uses: astral-sh/ruff-action@v3
